--话单质量统计表(周二\四)

select b.importdate '导入日期'
,b.batch '文件'
,b.branch '分公司'
,b.channel '渠道'
,b.cost '购买总价'
,b.price '购买单价'
,b.batchcnt '购买数量'
,case when b.batchcnt=0 then 0 else (b.batchcnt-b.importcnt)*1./b.batchcnt end '废弃率'
,case when b.batchcnt=0 then 0 else b.successcnt*1./b.batchcnt end '新增率'
,case when b.importcnt=0 then 0 else isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0)*1./b.importcnt end '拨打率'
,case when isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0)=0 then 0 else isnull(sum(t.isGetThrough),0)*1./isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0) end '首拨接通率'
,case when isnull(sum(t.isGetThrough),0)=0 then 0 else isnull(sum(t.isEnterProcess),0)*1./isnull(sum(t.isGetThrough),0) end '首拨转化率'
,case when isnull(sum(case when t.RequireAmount>0 then 1 else 0 end),0)=0 then 0 else isnull(sum(t.RequireAmount),0)*1./isnull(sum(case when t.RequireAmount>0 then 1 else 0 end),0) end '平均需求额'
,isnull(sum(t.ServiceTotal),0) '累计业绩'
,case when b.batchcnt=0 then 0 else (b.batchcnt*(1-(case when b.batchcnt=0 then 0 else (b.batchcnt-b.importcnt)*1./b.batchcnt end))*(case when isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0)=0 then 0 else isnull(sum(t.isGetThrough),0)*1./isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0) end)*(case when isnull(sum(t.isGetThrough),0)=0 then 0 else isnull(sum(t.isEnterProcess),0)*1./isnull(sum(t.isGetThrough),0) end)*(case when isnull(sum(case when t.RequireAmount>0 then 1 else 0 end),0)=0 then 0 else isnull(sum(t.RequireAmount),0)*1./isnull(sum(case when t.RequireAmount>0 then 1 else 0 end),0) end)*315/10-b.cost-b.batchcnt*2)/b.batchcnt end '首拨需求利润率'
,case when (b.batchcnt*(case when b.importcnt=0 then 0 else isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0)*1./b.importcnt end))=0 then 0 else ((isnull(sum(t.ServiceTotal_30days),0))-b.cost*(case when b.importcnt=0 then 0 else isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0)*1./b.importcnt end))/(b.batchcnt*(case when b.importcnt=0 then 0 else isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0)*1./b.importcnt end))-2 end '30天业绩利润率'
,case when (b.batchcnt*(case when b.importcnt=0 then 0 else isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0)*1./b.importcnt end))=0 then 0 else ((isnull(sum(t.ServiceTotal_45days),0))-b.cost*(case when b.importcnt=0 then 0 else isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0)*1./b.importcnt end))/(b.batchcnt*(case when b.importcnt=0 then 0 else isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0)*1./b.importcnt end))-2 end '45天业绩利润率'
,case when (b.cost+b.batchcnt*2)=0 then 0 else b.batchcnt*(1-(case when b.batchcnt=0 then 0 else (b.batchcnt-b.importcnt)*1./b.batchcnt end))*(case when isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0)=0 then 0 else isnull(sum(t.isGetThrough),0)*1./isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0) end)*(case when isnull(sum(t.isGetThrough),0)=0 then 0 else isnull(sum(t.isEnterProcess),0)*1./isnull(sum(t.isGetThrough),0) end)*(case when isnull(sum(case when t.RequireAmount>0 then 1 else 0 end),0)=0 then 0 else isnull(sum(t.RequireAmount),0)*1./isnull(sum(case when t.RequireAmount>0 then 1 else 0 end),0) end)*315/10/(b.cost+b.batchcnt*2) end '首拨需求投产比'
,case when b.batchcnt*(b.price+2)=0 then 0 else isnull(sum(t.serviceTotal_30days),0)*1./(b.batchcnt*(b.price+2)) end '30天业绩投产比'
,case when b.batchcnt*(b.price+2)=0 then 0 else isnull(sum(t.serviceTotal_45days),0)*1./(b.batchcnt*(b.price+2)) end '45天业绩投产比'
,(b.batchcnt-b.importcnt) '废弃话单量'
,b.importcnt '导入总量'
,b.successcnt '成功新增'
,isnull(sum(case when t.FirstCallDate is not null then 1 else 0 end),0) '拨打量'
,isnull(sum(t.isGetThrough),0) '首拨接通量'
,isnull(sum(t.isEnterProcess),0) '首拨有效进程量'
,isnull(sum(t.RequireAmount),0) '需求总额'
,isnull(sum(case when t.RequireAmount>0 then 1 else 0 end),0) '有需求客户数'
,isnull(sum(t.servicetotal_15days),0) '15天业绩'
,isnull(sum(t.serviceTotal_30days),0) '30天业绩'
,isnull(sum(t.serviceTotal_45days),0) '45天业绩'
,isnull(sum(t.calls),0) '拨打次数' 
,isnull(sum(t.getThroughs),0) '接通次数'
from dfss_bi..batchinfo b 
left join dfss_bi..telemarketingdetail t
on t.batch=b.batch
group by b.importdate,b.batch,b.branch,b.channel,b.cost,b.price,b.batchcnt,b.importcnt,b.successcnt
